fourth/devsearch/devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fourth/devsearch/projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/<str:pk>/', views.project, name='project'),
    path('create-project/', views.create_project, name='create-project'),
]

fourth/devsearch/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.user_profile, name='user_profile'),

    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_user, name="register")
]

fourth/devsearch/projects/models.py
from django.db import models
from users.models import Profile

# Create your models here.


class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    featured_image = models.ImageField(upload_to="projects/%Y/%m/%d/", default="default.jpg")
    demo_link = models.CharField(max_length=2000, blank=True)
    source_link = models.CharField(max_length=2000, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0)
    vote_rating = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

fourth/devsearch/users/models.py
from django.db import models
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=200, blank=True)
    email = models.EmailField(max_length=500, blank=True)
    username = models.CharField(max_length=200, blank=True)
    short_intro = models.CharField(max_length=200, blank=True)
    bio = models.TextField(blank=True)
    profile_image = models.ImageField(upload_to="profiles/", default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, blank=True)
    social_youtube = models.CharField(max_length=200, blank=True)
    social_website = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name




# Create your models here.

fourth/devsearch/projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'featured_image', 'description', 'demo_link', 'source_link', 'tags']
        widgets = {'tags': forms.CheckboxSelectMultiple()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

            # self.fields['title'].widget.attrs.update({'class': 'input'})

fourth/devsearch/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            "first_name": "Name"
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

fourth/devsearch/projects/views.py
from django.shortcuts import render, redirect
from .models import Project
from .forms import ProjectForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def projects(request):
    pr = Project.objects.all()
    context = {
        'projects': pr
    }

    return render(request, 'projects/projects.html', context)


def project(request, pk):
    project_obj = Project.objects.get(id=pk)
    context = {'project': project_obj}
    return render(request, "projects/single-project.html", context)

@login_required(login_url="login")
def create_project(request):
    form = ProjectForm()

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form': form}
    return render(request, 'projects/form-template.html', context)

fourth/devsearch/users/views.py
from django.shortcuts import render, redirect


from .models import Profile
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm


def profiles(request):
    prof = Profile.objects.all()
    context = {'profiles': prof}
    return render(request, 'users/index.html', context)


def user_profile(request, pk):
    prof = Profile.objects.get(id=pk)

    top_skills = prof.skill_set.exclude(description__exact="") #__exact - точное совпадение
    other_skills = prof.skill_set.filter(description="")

    context = {
        'profile': prof,
        'top_skills': top_skills,
        "other_skills": other_skills
    }

    return render(request, "users/profile.html", context)


def login_user(request):

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == "POST":
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except ObjectDoesNotExist:
            messages.error(request, "Username does not exist")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'Username or password is incorrect')


    return render(request, "users/login_register.html")


def logout_user(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('login')


def register_user(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == "POST":
        form = CustomUserCreationForm()
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, "User account was created!")
            login(request, user)
            return redirect('profiles')
    else:
        messages.error(request, 'An error has occurred during registration')

    context = {
        'page': page,
        'form': form
    }
    return render(request, 'users/login_register.html', context)

fourth/devsearch/projects/templates/projects/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - font-awesome -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css'%}" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>

{% include 'projects/navbar.html' %}

{% if messages %}
{% for message in messages %}
<div style="text-align: center" >
   <div class="alert alert--{{ message.tags }}">
            <p class="alert__message">{{ message }}</p>
            <button class="alert__close">⨯</button>
   </div>
</div>
{% endfor %}
{% endif %}

{% block content %}{% endblock %}
<script src="{% static 'uikit/app.js' %}"></script>

</body>

</html>

fourth/devsearch/projects/templates/projects/form-template.html
{% extends 'projects/base.html' %}
{% load static %}


{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><img src="{% static 'images/left.png' %}" alt="left"></a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- Input:Text -->
                    {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label }}</label>
                        {{field}}
                    </div>
                    {% endfor %}


                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>

{% endblock %}

fourth/devsearch/projects/templates/projects/navbar.html
{% load static %}

<!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'profiles' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>

          {% if request.user.is_authenticated %}
                    <li class="header__menuItem"><a href="{% url 'create-project' %}">Add Project</a></li>
          <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Logout</a></li>

          {% else %}
          <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

fourth/devsearch/projects/templates/projects/projects.html
{% extends 'projects/base.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">

          {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{ project.title }}</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{ project.vote_rating }}%</span> Postitive
                    Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
                  </p>
                  <div class="project__tags">
                    {% for tag in project.tags.all %}

                    <span class="tag tag--pill tag--main">
                      <small>{{ tag }}</small>
                      {% endfor %}
                    </span>

                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>

{% endblock %}

fourth/devsearch/projects/templates/projects/single-project.html
{% extends 'projects/base.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">

            {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ tag }}</small>
            </span>
            {% endfor %}

          </div>

          {% if project.source_link %}
          <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
          {% endif %}

          {% if project.demo_link %}
          <a class="singleProject__liveLink" href="{{ project.demo_link }}" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
          {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ project.featured_image.url }}" alt="portfolio thumbnail" />
          <a href="{% url 'user_profile' project.owner.id %} class="singleProject__developer">{{ project.owner.name }}</a>
          <h2 class="singleProject__title">{{ project.title }}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
              {{ project.description }}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              {{ project.vote_rating }}% Postitive Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
            </h5>

            <form class="form" action="#" method="POST">
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                  placeholder="Write your comments here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            <div class="commentList">
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md"
                    src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                  <p class="comment__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                    mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                    similique consequuntur ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                  <p class="comment__info">
                    Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                    exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>

{% endblock %}

fourth/devsearch/users/templates/users/index.html
{% extends 'projects/base.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user_profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{ profile.name }}</h3>
                    <h5>{{ profile.short_intro|slice:"60" }}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{ profile.bio|slice:"150" }}
                </p>
                <div class="dev__skills">

                  {% for skill in profile.skill_set.all|slice:"3" %}
                  <span class="tag tag--pill tag--main">
                    <small>{{ skill }}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>

{% endblock %}

fourth/devsearch/users/templates/users/login_register.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}

{% if page == 'register' %}
<!--<h1>Register User</h1>-->

<!--<form action="{% url 'register' %}" method="post">-->
<!--  {% csrf_token %}-->
<!--  {{ form }}-->
<!--  <input type="submit" value="Register">-->
<!--</form>-->

<!--<p>Already have on account <a href="{% url 'login' %}">Login</a></p>-->

    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/logo.svg' %}" alt="icon" />
          </a>
          <h3>Register an Account</h3>
          <p>Create a new developer account</p>
        </div>

        <form action="{% url 'register' %}" method="post" class="form auth__form">
          {% csrf_token %}

          {% for field in form %}
          <div class="form__field">
            <label for="formInput#text">{{ field.label }}: </label>
            {{ field }}
            {% for error in field.errors %}
            <p style="color:red">{{ error }}</p>
            {% endfor %}
          </div>
          {% endfor %}


          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="{% url 'login' %}">Log In</a>
        </div>
      </div>
    </div>



{% else %}

    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/logo.svg' %}" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <form action="{% url 'login' %}" method="post" class="form auth__form">
          {% csrf_token %}
            <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="forgetpassword.html">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'register' %}">Sign Up</a>
        </div>
      </div>
    </div>
{% endif %}

{% endblock %}

fourth/devsearch/users/templates/users/profile.html
{% extends 'projects/base.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="fa fa-github-square"></i></a>
                </li>
                {% endif %}
                {% if profile.social_youtube %}
                <li>
                  <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i class="fa fa-youtube"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="fa fa-sitemap"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}


            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in top_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">
                  {{ skill.description }}
                </p>
              </div>
              {% endfor %}



              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill }}</small>
                </span>
                {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.title }}</h3>
                      <p><a class="project__author" href="{% url 'user_profile' project.owner.id %}">By  {{ project.owner.name }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_rating }}%</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
                      </p>
                      <div class="project__tags">

                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{ tag }}</small>
                        </span>
                        {% endfor %}

                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}



            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}